name: CI

on:
    push:
        branches: spring-no-web

jobs: 
    continuos-integration:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v1
      
            - name: Deploy to sandbox via rsync
              uses: trendyminds/github-actions-rsync@master
              with:
                RSYNC_OPTIONS: -avzr --delete --exclude node_modules --exclude '.git*'
                RSYNC_TARGET: /path/to/target/folder/on/server
                RSYNC_SOURCE: /src/public/
              env:
                SSH_PRIVATE_KEY: ${{secrets.SSH}}
                SSH_USERNAME: ${{secrets.USERNAME}}
                SSH_HOSTNAME: ${{secrets.HOST}}
