name: scp files
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:      
    - uses: actions/checkout@v4
    - name: Run a multi-line script
      run: |
        mkdir ../build
        cp -TR . ../build
        tar -cvf deploy.tar ../build/
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: 3.83.202.88
        username: Administrator
        password: K8L6zInS62FgB1.F@RKx&Lj)dPc3b2Kf
        port: 22
        source: deploy.tar
        target: C:\
        