name: scp files
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: copy file via ssh password
      uses: appleboy/scp-action@v0.1.7
      with:
        host: 52.207.55.112
        username: guilherme
        password: teste*01
        port: 22
        source: ./*
        target: /c/Users/
        tar_dereference: true
        rm: true
        #teste firewall